### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by L-Qun**

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
Hi, can you order them alphabetically?

**Comment by L-Qun** [comment]
done

**Comment by L-Qun** [comment]
Can I also add some descriptions to the Jotai documentation? You can review and comment freely.

**Review by dai-shi — APPROVED** [review]
Thanks.

**Comment by dai-shi** [comment]
We are thinking about re-organizing docs so that they can include some community packages. Meanwhile, please keep using discussions.

**Pull request merged**
